// export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
// export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
// export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';


// export const FETCH_TEACHERS_REQUEST = 'FETCH_TEACHERS_REQUEST';
// export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS';
// export const FETCH_TEACHERS_FAILURE = 'FETCH_TEACHERS_FAILURE';



// export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
// export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
// export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';


// export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST';
// export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
// export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE';


// export const EDIT_STUDENT_REQUEST = 'EDIT_STUDENT_REQUEST';
// export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
// export const EDIT_STUDENT_FAILURE = 'EDIT_STUDENT_FAILURE';


// export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
// export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
// export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';


// export const ADD_COURSE_REQUEST = 'ADD_COURSE_REQUEST';
// export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
// export const ADD_COURSE_FAILURE = 'ADD_COURSE_FAILURE';


// export const EDIT_COURSE_REQUEST = 'EDIT_COURSE_REQUEST';
// export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS';
// export const EDIT_COURSE_FAILURE = 'EDIT_COURSE_FAILURE';


// export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
// export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
// export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';